controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /user/{name}
    controller: 'App\Controller\TestController::displayUser'

